version: '3.8'

services:
  client:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./client/:/usr/src/app/client
    command: sh -c 'yarn && yarn dev'
    ports:
      - '3000:3000'
      - '8080:8080'
    tty: true
